-- local wk = require("which-key")
--
-- wk.setup({
--     -- your configuration comes here
--     -- or leave it empty to use the default settings
--     -- refer to the configuration section below
-- })
--
-- wk.register({
--     ["<leader>f"] = { ":lua vim.lsp.buf.format()<CR>", "Format code" },
--     ["<leader>w"] = { ":w<CR>", "Save" },
--     ["<leader>q"] = { ":q<CR>", "Quit" },
--     -- Add more mappings here
-- }, { prefix = "<leader>" })
--
